Use correct UTC settings for crontab
rq/rq-scheduler pull request #300
Opened 2023-10-10 16:33 UTC by ross-spencer

Connected to: https://github.com/rq/rq-scheduler/issues/299

2024-02-28 23:15 UTC, resulyrt93 commented
hi team, what is the last status about this task?

2024-02-29 13:52 UTC, Harsh-Maheshwari commented
```
FutureWarning: Version 0.22.0+ of crontab will use datetime.utcnow() and
datetime.utcfromtimestamp() instead of datetime.now() and
datetime.fromtimestamp() as was previous. This had been a bug, which will be
remedied. If you would like to keep the *old* behavior:
`ct.next(..., default_utc=False)` . If you want to use the new behavior *now*:
`ct.next(..., default_utc=True)`. If you pass a datetime object with a tzinfo
attribute that is not None, timezones will *just work* to the best of their
ability. There are tests...
  next_time = cron.next(now=now, return_datetime=True)
```  
Is this warning being solved in this thread?

2024-05-23 07:32 UTC, canhlinh approved these changes
LGTM

2024-05-23 09:46 UTC, canhlinh requested changes

2024-05-23 09:46 UTC, canhlinh commented on rq_scheduler/utils.py
> +    now = datetime.now(timezone.utc)
I think this would be better

```
    tz = dateutil.tz.tzlocal() if use_local_timezone else dateutil.tz.UTC
    now = datetime.now(tz)
```

2024-11-16 13:49 UTC, closed without merging